# Import Libraries

In [4]:
import pandas as pd
import numpy as np

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

# Load Cleaned Dataset

In [5]:
master = pd.read_csv(
    'cleaned_master_dataset.csv'
)

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

# Check Dataset

In [6]:
master.shape

(82365, 39)

# Top 10 Revenue Categories

In [7]:
category_revenue = (
    master.groupby(
        'product_category_name_english'
    )['revenue']
    .sum()
    .sort_values(
        ascending=False
    )
)

category_revenue.head(10)

product_category_name_english
watches_gifts            743296.92
health_beauty            737409.81
bed_bath_table           625785.69
sports_leisure           590918.46
computers_accessories    540672.77
furniture_decor          440672.31
housewares               392340.16
cool_stuff               381264.17
auto                     360329.79
garden_tools             292393.44
Name: revenue, dtype: float64

# Top 10 States by Revenue

In [8]:
state_revenue = (
    master.groupby(
        'customer_state'
    )['revenue']
    .sum()
    .sort_values(
        ascending=False
    )
)

state_revenue.head(10)

customer_state
SP    3125614.30
RJ    1117654.26
MG     947023.26
RS     444412.84
PR     417989.93
BA     320978.06
SC     317551.69
GO     189863.17
DF     174281.56
ES     156958.06
Name: revenue, dtype: float64

# Most Used Payment Types

In [9]:
master[
    'payment_type'
].value_counts()

payment_type
credit_card    60809
boleto         16007
voucher         4352
debit_card      1191
not_defined        3
unknown            3
Name: count, dtype: int64

# Average Delivery Days

In [10]:
master[
    'delivery_days'
].mean()

np.float64(11.967146239300673)

# Delivery Status Distribution

In [11]:
master[
    'delivery_status'
].value_counts()

delivery_status
On Time    77125
Delayed     5240
Name: count, dtype: int64

# Save KPI Summary

In [12]:
kpi_summary = pd.DataFrame({

    'Metric':[
        'Total Revenue',
        'Total Customers',
        'Average Delivery Days'
    ],

    'Value':[

        master['revenue'].sum(),

        master['customer_unique_id'].nunique(),

        master['delivery_days'].mean()
    ]
})

kpi_summary

                  Metric         Value
0          Total Revenue  8.219744e+06
1        Total Customers  6.912700e+04
2  Average Delivery Days  1.196715e+01

# Top Revenue Categories

In [13]:
category_revenue.head(10)

product_category_name_english
watches_gifts            743296.92
health_beauty            737409.81
bed_bath_table           625785.69
sports_leisure           590918.46
computers_accessories    540672.77
furniture_decor          440672.31
housewares               392340.16
cool_stuff               381264.17
auto                     360329.79
garden_tools             292393.44
Name: revenue, dtype: float64

# Top States by Revenue

In [14]:
state_revenue.head(10)

customer_state
SP    3125614.30
RJ    1117654.26
MG     947023.26
RS     444412.84
PR     417989.93
BA     320978.06
SC     317551.69
GO     189863.17
DF     174281.56
ES     156958.06
Name: revenue, dtype: float64

# Payment Type Distribution

In [16]:
master['payment_type'].value_counts()

payment_type
credit_card    60809
boleto         16007
voucher         4352
debit_card      1191
not_defined        3
unknown            3
Name: count, dtype: int64

# Delivery Status Distribution

In [17]:
master['delivery_status'].value_counts()

delivery_status
On Time    77125
Delayed     5240
Name: count, dtype: int64

# KPI Summary

In [18]:
kpi_summary

                  Metric         Value
0          Total Revenue  8.219744e+06
1        Total Customers  6.912700e+04
2  Average Delivery Days  1.196715e+01

In [19]:
kpi_summary.to_csv(
    'kpi_summary.csv',
    index=False
)

print("KPI Summary Saved")

KPI Summary Saved

In [20]:
state_revenue.to_csv(
    'state_revenue.csv',
    index=False
)

print("State Revenue Saved")

State Revenue Saved

In [21]:
category_revenue.to_csv(
    'category_revenue.csv',
    index=False
)

print("Category Revenue Saved")

Category Revenue Saved

In [22]:
import os
os.listdir()

['.config',
 'category_revenue.csv',
 'kpi_summary.csv',
 'cleaned_master_dataset.csv',
 'state_revenue.csv',
 'sample_data']