In [1]:
import pandas as pd
import numpy as np

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
customer_churn = pd.read_csv(
    'customer_churn.csv'
)

product_category = pd.read_csv(
    'product_category_revenue.csv'
)

forecast_summary = pd.read_csv(
    'forecast_summary.csv'
)

cluster_summary = pd.read_csv(
    'cluster_summary.csv'
)

print("Datasets Loaded Successfully")

Datasets Loaded Successfully

# Revenue Insight

In [3]:
top_category = (
    product_category
    .sort_values(
        'revenue',
        ascending=False
    )
    .iloc[0]
)

print(
    f"Top Revenue Category: {top_category.iloc[0]}"
)

Top Revenue Category: watches_gifts

# Churn Insight

In [4]:
critical_customers = (
    customer_churn[
        customer_churn[
            'Risk_Level'
        ] == 'Critical Risk'
    ]
    .shape[0]
)

print(
    f"Critical Risk Customers: {critical_customers}"
)

Critical Risk Customers: 49162

# Cluster Insight

In [5]:
cluster_summary.head()

   Cluster  Total_Revenue  Total_Orders  Average_Order_Value
0        0      75.949204      1.000000            75.949204
1        1     530.676332      1.000000           530.676332
2        2     205.474082      2.096835            98.281760
3        3    2068.722748      1.027228          2029.076658

In [8]:
print(cluster_summary.columns.tolist())

['Cluster', 'Total_Revenue', 'Total_Orders', 'Average_Order_Value']

In [9]:
best_cluster = (
    cluster_summary
    .sort_values(
        'Total_Revenue',
        ascending=False
    )
    .iloc[0]
)

print(
    "Highest Revenue Cluster:",
    best_cluster['Cluster']
)

print(
    "Revenue:",
    round(best_cluster['Total_Revenue'], 2)
)

Highest Revenue Cluster: 3.0
Revenue: 2068.72

In [48]:
best_cluster = (
    cluster_summary
    .sort_values(
        'Total_Revenue',
        ascending=False
    )
    .iloc[0]
)

print(
    f"Cluster {best_cluster['Cluster']} is the highest revenue generating customer segment with revenue of {round(best_cluster['Total_Revenue'],2)}."
)

Cluster 3.0 is the highest revenue generating customer segment with revenue of 2068.72.

# Forecast Insight

In [11]:
forecast_summary

                       Metric          Value
0  Average Historical Revenue  328789.774800
1    Average Forecast Revenue  572903.384327
2           Forecast Growth %      74.246107

In [12]:
print(
    "Forecast analysis indicates positive future revenue trends."
)

Forecast analysis indicates positive future revenue trends.

# Generate Executive Recommendations

In [13]:
insights = [

    "Focus retention campaigns on critical-risk customers.",

    "Increase investment in top-performing categories.",

    "Target high-value customer clusters.",

    "Monitor forecasted revenue changes monthly.",

    "Develop personalised offers for churn-prone customers."
]

for i in insights:

    print(i)

Focus retention campaigns on critical-risk customers.
Increase investment in top-performing categories.
Target high-value customer clusters.
Monitor forecasted revenue changes monthly.
Develop personalised offers for churn-prone customers.

In [14]:
insight_df = pd.DataFrame({
    'Business_Insights': insights
})

insight_df.to_csv(
    'ai_business_insights.csv',
    index=False
)

print(
    "AI Insights Exported"
)

AI Insights Exported

# Revenue Performance Intelligence

In [15]:
top_category = (
    product_category
    .sort_values(
        'revenue',
        ascending=False
    )
    .iloc[0]
)

lowest_category = (
    product_category
    .sort_values(
        'revenue'
    )
    .iloc[0]
)

print(
    f"Top performing category is {top_category.iloc[0]} with revenue of {round(top_category['revenue'],2)}."
)

print(
    f"Lowest performing category is {lowest_category.iloc[0]} with revenue of {round(lowest_category['revenue'],2)}."
)

Top performing category is watches_gifts with revenue of 743296.92.
Lowest performing category is security_and_services with revenue of 283.29.

# Customer Risk Intelligence

In [16]:
risk_summary = (
    customer_churn[
        'Risk_Level'
    ]
    .value_counts()
)

print(
    "Customer Risk Distribution:"
)

print(risk_summary)

Customer Risk Distribution:
Risk_Level
Critical Risk    49162
Medium Risk       9657
High Risk         9219
Low Risk          1089
Name: count, dtype: int64

In [17]:
critical_count = risk_summary.get(
    'Critical Risk',
    0
)

if critical_count > 10000:

    print(
        "AI Recommendation: Immediate retention campaigns should be launched for critical-risk customers."
    )

else:

    print(
        "AI Recommendation: Customer retention is currently stable."
    )

AI Recommendation: Immediate retention campaigns should be launched for critical-risk customers.

# Cluster Intelligence Engine

In [18]:
best_cluster = (
    cluster_summary
    .sort_values(
        'Total_Revenue',
        ascending=False
    )
    .iloc[0]
)

print(
    f"Cluster {best_cluster['Cluster']} contributes the highest revenue and should be prioritised for premium offers."
)

Cluster 3.0 contributes the highest revenue and should be prioritised for premium offers.

# Revenue Forecast Intelligence

In [19]:
forecast_avg = (
    forecast_summary[
        'Value'
    ]
    .mean()
)

print(
    f"Average forecast indicator value: {round(forecast_avg,2)}"
)

Average forecast indicator value: 300589.14

In [21]:
churn_rate = (
    customer_churn['Churn']
    .mean()
    * 100
)

print(
    "Churn Rate:",
    round(churn_rate, 2),
    "%"
)

Churn Rate: 90.13 %

In [22]:
historical_revenue = (
    forecast_summary[
        forecast_summary['Metric']
        ==
        'Average Historical Revenue'
    ]['Value']
    .iloc[0]
)

forecast_revenue = (
    forecast_summary[
        forecast_summary['Metric']
        ==
        'Average Forecast Revenue'
    ]['Value']
    .iloc[0]
)

forecast_growth = (
    (
        forecast_revenue
        -
        historical_revenue
    )
    /
    historical_revenue
) * 100

print(
    "Forecast Growth:",
    round(forecast_growth, 2),
    "%"
)

Forecast Growth: 74.25 %

# Business Health Score

In [23]:
health_score = 100

if critical_count > 10000:
    health_score -= 25

if churn_rate > 70:
    health_score -= 25

if forecast_growth < 0:
    health_score -= 25

print(
    "Business Health Score:",
    health_score,
    "/100"
)

Business Health Score: 50 /100

In [24]:
health_score = 100

if critical_count > 10000:
    health_score -= 20

if churn_rate > 70:
    health_score -= 20

if forecast_growth < 0:
    health_score -= 20

if top_category['revenue'] < 100000:
    health_score -= 20

health_score = max(
    health_score,
    0
)

print(
    "Business Health Score:",
    health_score,
    "/100"
)

Business Health Score: 60 /100

# Revenue Opportunity Detector

In [25]:
top5_categories = (
    product_category
    .sort_values(
        'revenue',
        ascending=False
    )
    .head(5)
)

print(
    "Top Revenue Opportunities:"
)

print(
    top5_categories
)

Top Revenue Opportunities:
  product_category_name_english    revenue
0                 watches_gifts  743296.92
1                 health_beauty  737409.81
2                bed_bath_table  625785.69
3                sports_leisure  590918.46
4         computers_accessories  540672.77

# AI Executive Summary Generator

In [26]:
executive_summary = f"""

BUSINESS EXECUTIVE SUMMARY

• Highest Revenue Cluster: {best_cluster['Cluster']}

• Critical Risk Customers: {critical_count}

• Business Health Score: {health_score}/100

• Top Revenue Category: {top_category.iloc[0]}

• Strategic Focus:
  Increase retention efforts,
  focus on high-value clusters,
  and expand top-performing categories.

"""

print(executive_summary)

BUSINESS EXECUTIVE SUMMARY

• Highest Revenue Cluster: 3.0

• Critical Risk Customers: 49162

• Business Health Score: 60/100

• Top Revenue Category: watches_gifts

• Strategic Focus:
  Increase retention efforts,
  focus on high-value clusters,
  and expand top-performing categories.

# Smart Recommendation Engine

In [27]:
recommendations = []

if critical_count > 10000:
    recommendations.append(
        "Launch customer retention campaigns."
    )

if health_score < 70:
    recommendations.append(
        "Improve customer engagement programmes."
    )

recommendations.append(
    "Invest in top-performing product categories."
)

recommendations.append(
    "Prioritise high-value customer clusters."
)

for rec in recommendations:

    print(
        "Recommendation:",
        rec
    )

Recommendation: Launch customer retention campaigns.
Recommendation: Improve customer engagement programmes.
Recommendation: Invest in top-performing product categories.
Recommendation: Prioritise high-value customer clusters.

# Export AI Intelligence Report

In [28]:
ai_report = pd.DataFrame({
    'Recommendation': recommendations
})

ai_report.to_csv(
    'ai_intelligence_report.csv',
    index=False
)

print(
    "AI Intelligence Report Exported"
)

AI Intelligence Report Exported

# Customer Lifetime Intelligence

In [31]:
high_value_customers = (
    pd.read_csv('customer_cltv.csv')
)

top_customers = (
    high_value_customers
    .sort_values(
        'CLTV',
        ascending=False
    )
    .head(10)
)

print(
    "Top 10 High Value Customers"
)

top_customers

Top 10 High Value Customers

,customer_unique_id,total_revenue,total_orders,average_order_value,CLTV,CLTV_Segment
2717,0a0a92112bd4c708ca5fde585afaa872,13440.0,1,13440.0,13440.0,Premium Value
53160,c4b224d2c784bae11ae98b6ae9f2454c,10856.1,1,10856.1,10856.1,Premium Value
36004,85963fd37bfd387aa6d915d8a1065486,9888.0,1,9888.0,9888.0,Premium Value
64299,edf81e1f3070b9dac83ec83dacdbb9bc,7998.0,1,7998.0,7998.0,Premium Value
4422,1033eef37a760a832f9b2332ce23fdc5,7799.4,1,7799.4,7799.4,Premium Value
58989,da122df9eeddfedc1dc1f5349a1a690c,7388.0,2,3694.0,7388.0,Premium Value
31853,763c8b1c9c68a0229c42c9fc6f662b93,7160.0,1,7160.0,7160.0,Premium Value
59595,dc4802a71eae9be1dd28f5d788ceb526,6735.0,1,6735.0,6735.0,Premium Value
17288,4007669dec559734d6f53e029e360987,5934.6,1,5934.6,5934.6,Premium Value
68429,fd7069cf6891edbf32ba84c9c3f083d4,5814.0,1,5814.0,5814.0,Premium Value

In [32]:
print(
    f"AI Insight: Top 10 customers contribute significant lifetime value and should receive personalised retention campaigns."
)

AI Insight: Top 10 customers contribute significant lifetime value and should receive personalised retention campaigns.

# Revenue Concentration Risk

In [37]:
top_share = (
    product_category['revenue']
    .max()
    /
    product_category['revenue']
    .sum()
) * 100

print(
    "Revenue Concentration:",
    round(top_share,2),
    "%"
)

Revenue Concentration: 9.04 %

In [38]:
if top_share > 40:

    print(
        "AI Alert: Revenue is highly dependent on a single category."
    )

else:

    print(
        "AI Insight: Revenue diversification is healthy."
    )

AI Insight: Revenue diversification is healthy.

# Churn Revenue Impact

In [39]:
critical_customers = (
    customer_churn[
        customer_churn[
            'Risk_Level'
        ]
        ==
        'Critical Risk'
    ]
)

print(
    "Critical Risk Customers:",
    len(critical_customers)
)

Critical Risk Customers: 49162

In [40]:
print(
    "AI Insight: Critical-risk customers should be prioritised for retention campaigns."
)

AI Insight: Critical-risk customers should be prioritised for retention campaigns.

# Customer Cluster Opportunity Ranking

In [41]:
cluster_ranking = (
    cluster_summary
    .sort_values(
        'Total_Revenue',
        ascending=False
    )
)

cluster_ranking

   Cluster  Total_Revenue  Total_Orders  Average_Order_Value
3        3    2068.722748      1.027228          2029.076658
1        1     530.676332      1.000000           530.676332
2        2     205.474082      2.096835            98.281760
0        0      75.949204      1.000000            75.949204

In [42]:
print(
    f"Cluster {cluster_ranking.iloc[0]['Cluster']} offers the highest business opportunity."
)

Cluster 3.0 offers the highest business opportunity.

# Business KPI Scorecard

In [43]:
kpi_scorecard = pd.DataFrame({

    'Metric':[
        'Business Health',
        'Churn Rate',
        'Forecast Growth'
    ],

    'Value':[
        health_score,
        round(churn_rate,2),
        round(forecast_growth,2)
    ]

})

kpi_scorecard

            Metric  Value
0  Business Health  60.00
1       Churn Rate  90.13
2  Forecast Growth  74.25

# AI Risk Detector

In [44]:
risks = []

if churn_rate > 70:
    risks.append(
        "High customer churn detected"
    )

if forecast_growth < 0:
    risks.append(
        "Revenue decline predicted"
    )

if critical_count > 10000:
    risks.append(
        "Large number of critical customers"
    )

for risk in risks:

    print(
        "Risk:",
        risk
    )

Risk: High customer churn detected
Risk: Large number of critical customers

# AI Opportunity Detector

In [45]:
opportunities = []

opportunities.append(
    "Expand top-performing categories"
)

opportunities.append(
    "Target high-value customer clusters"
)

opportunities.append(
    "Improve retention for critical customers"
)

for opportunity in opportunities:

    print(
        "Opportunity:",
        opportunity
    )

Opportunity: Expand top-performing categories
Opportunity: Target high-value customer clusters
Opportunity: Improve retention for critical customers

# AI Management Report Generator

In [46]:
management_report = f"""

EXECUTIVE MANAGEMENT REPORT

Business Health Score : {health_score}/100

Churn Rate : {round(churn_rate,2)}%

Forecast Growth : {round(forecast_growth,2)}%

Critical Risk Customers : {critical_count}

Highest Revenue Cluster : {best_cluster['Cluster']}

Strategic Recommendations:

1. Focus on customer retention.

2. Invest in top-performing categories.

3. Expand high-value customer segments.

4. Monitor churn and forecast trends monthly.

"""

print(
    management_report
)

EXECUTIVE MANAGEMENT REPORT

Business Health Score : 60/100

Churn Rate : 90.13%

Forecast Growth : 74.25%

Critical Risk Customers : 49162

Highest Revenue Cluster : 3.0

Strategic Recommendations:

1. Focus on customer retention.

2. Invest in top-performing categories.

3. Expand high-value customer segments.

4. Monitor churn and forecast trends monthly.

In [47]:
management_df = pd.DataFrame({
    'Management_Report':
    [management_report]
})

management_df.to_csv(
    'management_report.csv',
    index=False
)

print(
    "Management Report Exported"
)

Management Report Exported