In [25]:
import pandas as pd
import numpy as np
Anomaly Risk LevelAnomaly Risk Level
print(
    "Libraries Loaded Successfully"
)

Libraries Loaded Successfully

In [26]:
customer_360 = pd.read_csv(
    'customer_360.csv'
)

executive_dashboard = pd.read_csv(
    'executive_dashboard.csv'
)

print(
    "Datasets Loaded Successfully"
)

Datasets Loaded Successfully

# Customer Health Anomaly Detection

In [27]:
health_threshold = (

    customer_360[
        'Customer_Health_Index'
    ].mean()

    -

    2 *

    customer_360[
        'Customer_Health_Index'
    ].std()

)

health_anomalies = (

    customer_360[
        customer_360[
            'Customer_Health_Index'
        ] < health_threshold
    ]

)

print(
    "Health Anomalies:",
    len(
        health_anomalies
    )
)

Health Anomalies: 0

# Risk Anomaly Detection

In [28]:
risk_threshold = (

    customer_360[
        'Dynamic_Risk_Score'
    ].mean()

    +

    2 *

    customer_360[
        'Dynamic_Risk_Score'
    ].std()

)

risk_anomalies = (

    customer_360[
        customer_360[
            'Dynamic_Risk_Score'
        ] > risk_threshold
    ]

)

print(
    "Risk Anomalies:",
    len(
        risk_anomalies
    )
)

Risk Anomalies: 0

# Strategic Value Anomaly Detection

In [29]:
value_threshold = (

    customer_360[
        'Strategic_Value_Score'
    ].mean()

    +

    2 *

    customer_360[
        'Strategic_Value_Score'
    ].std()

)

value_anomalies = (

    customer_360[
        customer_360[
            'Strategic_Value_Score'
        ] > value_threshold
    ]

)

print(
    "Strategic Value Anomalies:",
    len(
        value_anomalies
    )
)

Strategic Value Anomalies: 6826

# Anomaly Summary

In [30]:
anomaly_summary = pd.DataFrame({

    'Anomaly_Type':[

        'Health',

        'Risk',

        'Strategic Value'

    ],

    'Count':[

        len(
            health_anomalies
        ),

        len(
            risk_anomalies
        ),

        len(
            value_anomalies
        )

    ]

})

anomaly_summary

      Anomaly_Type  Count
0           Health      0
1             Risk      0
2  Strategic Value   6826

# Business Alert Engine

In [31]:
alerts = []

if len(health_anomalies) > 1000:

    alerts.append(
        "Customer health decline detected."
    )

if len(risk_anomalies) > 1000:

    alerts.append(
        "Customer risk surge detected."
    )

if len(value_anomalies) > 500:

    alerts.append(
        "High-value customer concentration detected."
    )

for alert in alerts:

    print(
        "ALERT:",
        alert
    )

ALERT: High-value customer concentration detected.

# Anomaly Risk Level

In [32]:
total_anomalies = (

    len(
        health_anomalies
    )

    +

    len(
        risk_anomalies
    )

    +

    len(
        value_anomalies
    )

)

if total_anomalies > 5000:

    anomaly_risk = (
        "High"
    )

elif total_anomalies > 1000:

    anomaly_risk = (
        "Medium"
    )

else:

    anomaly_risk = (
        "Low"
    )

print(
    "Business Anomaly Risk:",
    anomaly_risk
)

Business Anomaly Risk: High

In [33]:
health_anomalies.to_csv(
    'health_anomalies.csv',
    index=False
)

risk_anomalies.to_csv(
    'risk_anomalies.csv',
    index=False
)

value_anomalies.to_csv(
    'value_anomalies.csv',
    index=False
)

anomaly_summary.to_csv(
    'anomaly_summary.csv',
    index=False
)

print(
    "Anomaly Datasets Exported Successfully"
)

Anomaly Datasets Exported Successfully

# Anomaly Severity Score

In [34]:
anomaly_summary['Severity_Score'] = (

    anomaly_summary['Count']

    /

    anomaly_summary['Count'].max()

) * 100

anomaly_summary

      Anomaly_Type  Count  Severity_Score
0           Health      0             0.0
1             Risk      0             0.0
2  Strategic Value   6826           100.0

# Anomaly Severity Classification

In [35]:
anomaly_summary[
    'Severity_Level'
] = np.where(

    anomaly_summary[
        'Severity_Score'
    ] > 75,

    'Critical',

    np.where(

        anomaly_summary[
            'Severity_Score'
        ] > 40,

        'Moderate',

        'Low'

    )

)

anomaly_summary

      Anomaly_Type  Count  Severity_Score Severity_Level
0           Health      0             0.0            Low
1             Risk      0             0.0            Low
2  Strategic Value   6826           100.0       Critical

# Executive Alert Dashboard

In [36]:
executive_alerts = []

for _, row in anomaly_summary.iterrows():

    if row[
        'Severity_Level'
    ] == 'Critical':

        executive_alerts.append(

            f"{row['Anomaly_Type']} anomaly requires immediate investigation."

        )

for alert in executive_alerts:

    print(
        alert
    )

Strategic Value anomaly requires immediate investigation.

# Predictive Anomaly Risk Score

In [37]:
predictive_risk = (

    anomaly_summary[
        'Severity_Score'
    ].mean()

)

print(
    "Predictive Anomaly Risk:",
    round(
        predictive_risk,
        2
    )
)

Predictive Anomaly Risk: 33.33

# AI Root Cause Analysis

In [38]:
print(
    "AI ROOT CAUSE ANALYSIS"
)

print(
    "------------------------"
)

if len(risk_anomalies) > len(health_anomalies):

    print(
        "Primary issue appears to be elevated customer risk."
    )

elif len(health_anomalies) > len(risk_anomalies):

    print(
        "Primary issue appears to be declining customer health."
    )

else:

    print(
        "Business metrics appear balanced."
    )

AI ROOT CAUSE ANALYSIS
------------------------
Business metrics appear balanced.

# AI Recommended Actions

In [39]:
actions = [

    "Investigate critical anomaly segments.",

    "Review customer retention strategies.",

    "Monitor high-risk customers weekly.",

    "Protect high-value customer groups.",

    "Track anomaly trends through dashboards."

]

for action in actions:

    print(
        action
    )

Investigate critical anomaly segments.
Review customer retention strategies.
Monitor high-risk customers weekly.
Protect high-value customer groups.
Track anomaly trends through dashboards.

In [40]:
anomaly_summary.to_csv(
    'anomaly_intelligence_summary.csv',
    index=False
)