In [1]:
import pandas as pd
import numpy as np

print(
    "Libraries Loaded Successfully"
)

Libraries Loaded Successfully

In [2]:
customer_360_master = pd.read_csv(
    'customer_360_master.csv'
)

revenue_forecast = pd.read_csv(
    'revenue_forecast.csv'
)

print(
    "Datasets Loaded Successfully"
)

Datasets Loaded Successfully

# Current Business Snapshot

In [3]:
current_customers = len(
    customer_360_master
)

current_avg_cltv = round(

    customer_360_master[
        'CLTV'
    ].mean(),

    2

)

current_revenue = round(

    customer_360_master[
        'CLTV'
    ].sum(),

    2

)

print(
    "Customers:",
    current_customers
)

print(
    "Average CLTV:",
    current_avg_cltv
)

print(
    "Current Revenue:",
    current_revenue
)

Customers: 69127
Average CLTV: 118.91
Current Revenue: 8219744.37

# Revenue Growth Simulation

In [4]:
growth_rates = [

    5,
    10,
    15,
    20

]

revenue_growth = []

for rate in growth_rates:

    future_revenue = (

        current_revenue

        *

        (
            1
            +
            rate/100
        )

    )

    revenue_growth.append([

        rate,

        round(
            future_revenue,
            2
        )

    ])

revenue_growth_df = pd.DataFrame(

    revenue_growth,

    columns=[

        'Growth_%',

        'Projected_Revenue'

    ]

)

revenue_growth_df

   Growth_%  Projected_Revenue
0         5         8630731.59
1        10         9041718.81
2        15         9452706.03
3        20         9863693.24

# Churn Reduction Simulation

In [5]:
current_churn = (

    customer_360_master[
        'Churn_Probability'
    ].mean()

)

reductions = [

    5,
    10,
    15,
    20

]

churn_simulation = []

for reduction in reductions:

    new_churn = (

        current_churn

        *

        (
            1
            -
            reduction/100
        )

    )

    churn_simulation.append([

        reduction,

        round(
            new_churn,
            2
        )

    ])

churn_simulation_df = pd.DataFrame(

    churn_simulation,

    columns=[

        'Reduction_%',

        'Projected_Churn'

    ]

)

churn_simulation_df

   Reduction_%  Projected_Churn
0            5             0.86
1           10             0.81
2           15             0.77
3           20             0.72

# Retention Improvement

In [6]:
retention_rates = [

    5,
    10,
    15,
    20

]

retention_scenarios = []

for rate in retention_rates:

    improved_cltv = (

        current_avg_cltv

        *

        (
            1
            +
            rate/100
        )

    )

    retention_scenarios.append([

        rate,

        round(
            improved_cltv,
            2
        )

    ])

retention_df = pd.DataFrame(

    retention_scenarios,

    columns=[

        'Retention_Improvement_%',

        'Projected_CLTV'

    ]

)

retention_df

   Retention_Improvement_%  Projected_CLTV
0                        5          124.86
1                       10          130.80
2                       15          136.75
3                       20          142.69

# High Risk Customer Recovery Scenario

In [7]:
high_risk = customer_360_master[

    customer_360_master[
        'Churn_Probability'
    ] > 0.7

]

recoveries = [

    10,
    20,
    30,
    40

]

recovery_results = []

for r in recoveries:

    retained_customers = int(

        len(high_risk)

        *

        (
            r/100
        )

    )

    recovery_results.append([

        r,

        retained_customers

    ])

recovery_df = pd.DataFrame(

    recovery_results,

    columns=[

        'Recovery_%',

        'Customers_Saved'

    ]

)

recovery_df

   Recovery_%  Customers_Saved
0          10             6230
1          20            12461
2          30            18691
3          40            24922

# Strategic Growth Scenario

In [8]:
strategic_growth = []

for growth in [

    10,
    20,
    30,
    40

]:

    projected_value = (

        customer_360_master[
            'Strategic_Value_Score'
        ].mean()

        *

        (
            1
            +
            growth/100
        )

    )

    strategic_growth.append([

        growth,

        round(
            projected_value,
            2
        )

    ])

strategic_growth_df = pd.DataFrame(

    strategic_growth,

    columns=[

        'Growth_%',

        'Projected_Strategic_Value'

    ]

)

strategic_growth_df

   Growth_%  Projected_Strategic_Value
0        10                      22.75
1        20                      24.82
2        30                      26.89
3        40                      28.95

# Executive Scenario Summary

In [9]:
scenario_summary = pd.DataFrame({

    'Scenario':[

        'Revenue Growth',

        'Churn Reduction',

        'Retention Improvement',

        'Customer Recovery',

        'Strategic Growth'

    ],

    'Status':[

        'Completed',

        'Completed',

        'Completed',

        'Completed',

        'Completed'

    ]

})

scenario_summary

                Scenario     Status
0         Revenue Growth  Completed
1        Churn Reduction  Completed
2  Retention Improvement  Completed
3      Customer Recovery  Completed
4       Strategic Growth  Completed

In [10]:
revenue_growth_df.to_csv(
    'revenue_growth_scenarios.csv',
    index=False
)

churn_simulation_df.to_csv(
    'churn_reduction_scenarios.csv',
    index=False
)

retention_df.to_csv(
    'retention_improvement_scenarios.csv',
    index=False
)

recovery_df.to_csv(
    'customer_recovery_scenarios.csv',
    index=False
)

strategic_growth_df.to_csv(
    'strategic_growth_scenarios.csv',
    index=False
)

print(
    "Scenario Simulation Datasets Exported Successfully"
)

Scenario Simulation Datasets Exported Successfully

# Estimate return on investment under different growth scenarios.

In [11]:
investment = 100000

roi_results = []

for growth in [5,10,15,20]:

    projected_return = (
        investment
        *
        (1 + growth/100)
    )

    roi = (
        (
            projected_return
            -
            investment
        )
        /
        investment
    ) * 100

    roi_results.append([
        growth,
        round(projected_return,2),
        round(roi,2)
    ])

roi_df = pd.DataFrame(

    roi_results,

    columns=[
        'Growth_%',
        'Projected_Return',
        'ROI_%'
    ]

)

roi_df

   Growth_%  Projected_Return  ROI_%
0         5          105000.0    5.0
1        10          110000.0   10.0
2        15          115000.0   15.0
3        20          120000.0   20.0

# Evaluate business impact of increasing marketing expenditure.

In [12]:
marketing_budget = 50000

budget_scenarios = []

for increase in [

    10,
    20,
    30,
    40

]:

    new_budget = (

        marketing_budget

        *

        (
            1
            +
            increase/100
        )

    )

    budget_scenarios.append([

        increase,

        round(
            new_budget,
            2
        )

    ])

marketing_budget_df = pd.DataFrame(

    budget_scenarios,

    columns=[

        'Budget_Increase_%',

        'Projected_Budget'

    ]

)

marketing_budget_df

   Budget_Increase_%  Projected_Budget
0                 10           55000.0
1                 20           60000.0
2                 30           65000.0
3                 40           70000.0

# Analyse customer acquisition efficiency.

In [13]:
cac = 100

cac_results = []

for reduction in [

    5,
    10,
    15,
    20

]:

    new_cac = (

        cac

        *

        (
            1
            -
            reduction/100
        )

    )

    cac_results.append([

        reduction,

        round(
            new_cac,
            2
        )

    ])

cac_df = pd.DataFrame(

    cac_results,

    columns=[

        'CAC_Reduction_%',

        'Projected_CAC'

    ]

)

cac_df

   CAC_Reduction_%  Projected_CAC
0                5           95.0
1               10           90.0
2               15           85.0
3               20           80.0

# Estimate future profitability under different growth levels.

In [14]:
profitability_results = []

profit_margin = 20

for growth in [

    5,
    10,
    15,
    20

]:

    projected_profit = (

        current_revenue

        *

        (
            growth/100
        )

        *

        (
            profit_margin/100
        )

    )

    profitability_results.append([

        growth,

        round(
            projected_profit,
            2
        )

    ])

profitability_df = pd.DataFrame(

    profitability_results,

    columns=[

        'Growth_%',

        'Projected_Profit'

    ]

)

profitability_df

   Growth_%  Projected_Profit
0         5          82197.44
1        10         164394.89
2        15         246592.33
3        20         328789.77

# Executive What-If Dashboard

In [15]:
executive_whatif = pd.DataFrame({

    'Scenario':[

        'Revenue Growth',

        'Churn Reduction',

        'Retention Improvement',

        'Customer Recovery',

        'Marketing Budget',

        'CAC Reduction',

        'Profitability'

    ],

    'Status':[

        'Analysed',

        'Analysed',

        'Analysed',

        'Analysed',

        'Analysed',

        'Analysed',

        'Analysed'

    ]

})

executive_whatif

                Scenario    Status
0         Revenue Growth  Analysed
1        Churn Reduction  Analysed
2  Retention Improvement  Analysed
3      Customer Recovery  Analysed
4       Marketing Budget  Analysed
5          CAC Reduction  Analysed
6          Profitability  Analysed

# Executive Strategy Score

In [16]:
strategy_score = (

    customer_360_master[
        'Strategic_Value_Score'
    ].mean()

    +

    customer_360_master[
        'Customer_Health_Index'
    ].mean()

) / 2

print(
    "Executive Strategy Score:",
    round(
        strategy_score,
        2
    )
)

Executive Strategy Score: 24.92

In [17]:
roi_df.to_csv(
    'roi_simulation.csv',
    index=False
)

marketing_budget_df.to_csv(
    'marketing_budget_simulation.csv',
    index=False
)

cac_df.to_csv(
    'cac_simulation.csv',
    index=False
)

profitability_df.to_csv(
    'profitability_simulation.csv',
    index=False
)

executive_whatif.to_csv(
    'executive_whatif_dashboard.csv',
    index=False
)

print(
    "Advanced Scenario Simulation Files Exported Successfully"
)

Advanced Scenario Simulation Files Exported Successfully